### ISSUE TITLE
Hector build: CTemplate issues under cray compiler.

### ISSUE THREAD

**Issue by schmie** [schmie/hemeMove#129]
**Reported by jamespjh on 22 Dec 2011 14:16 UTC**
CTemplate headers don't compile on Hector with the Cray compilers, only with the GNU compilers. This seems to be due to the fact that CTemplate uses the C++ TR1 unordered_map container.

This might mean that we can't use CTemplate, if we're committed to not using anything the cray compilers don't like.

**Comment by schmie** [comment]
**Comment by jamespjh on 22 Dec 2011 14:19 UTC**

I only just spotted this, because the 'hector' Jenkins node was actually pointing at legion, which revealed this when I fixed it.

I've switched Hector to the gnu compilers for now, see [also added options to the CMake build to choose the static versions of CTemplate and CPPUNIT, because the gnu linker on hector didn't like the shared library versions of these, see [1439](1435].

I) [and [1441](1440])

**Comment by schmie** [comment]
**Comment by jamespjh on 22 Dec 2011 14:21 UTC**
Possibly we could use https://github.com/breckinloggins/ngtemplate, which is a smaller and simpler pure-C solution which is syntax-compatible with CTemplate.

**Comment by schmie** [comment]
**Modified by jamespjh on 22 Dec 2011 15:59 UTC**

**Comment by schmie** [comment]
**Comment by jamespjh on 22 Dec 2011 18:18 UTC**
Although building with the gnu compilers apparently builds ok, the executables produced on Hector just seem horribly broken:
```

gdb) run
Starting program: /nfs02/e10/e10/jamespjh/FabricHemeLb/install/bin/hemelb 
[debugging using libthread_db enabled](Thread)

Program received signal SIGILL, Illegal instruction.
0x0000000000400a55 in std::numeric_limits<double>::max() ()
Current language:  auto
The current source language is "auto; currently c++".
(gdb) bt
#0  0x0000000000400a55 in std::numeric_limits<double>::max() ()
#1  0x000000000047242f in __static_initialization_and_destruction_0 ()
#2  0x000000000047246d in _GLOBAL__sub_I__ZN6hemelb2io11PathManagerC2ERKNS_13configuration11CommandLineERKbRKi ()
#3  0x00000000006b40f6 in __do_global_ctors_aux ()
#4  0x00000000004001db in _init ()
#5  0x000000000063b400 in ?? () at elf-init.c:100
#6  0x000000000063b49e in __libc_csu_init (argc=1, argv=0x7fffffffba38, envp=0x7fffffffba48) at elf-init.c:120
#7  0x000000000063af04 in __libc_start_main (main=0x4004d4 <main>, argc=1, ubp_av=0x7fffffffba38, init=0x63b440 <__libc_csu_init>, fini=0x63b400 <__libc_csu_fini>, 
    rtld_fini=0, stack_end=0x7fffffffba28) at libc-start.c:185

```

So we may need another solution. I will think.

**Comment by schmie** [comment]
**Comment by jamespjh on 22 Dec 2011 18:36 UTC**
The cray compilers version of the unittests doesn't work either, though it seems less broken: (I managed to build it by commenting out use of ctemplate.)

```

TimersBase (this=0xb01f90) at /home/e10/e10/jamespjh/FabricHemeLb/build/hemelb-prefix/src/hemelb/reporting/Timers.h:90
90	            timers(numberOfTimers), maxes(numberOfTimers), mins(numberOfTimers), means(numberOfTimers)
(gdb) bt
#0  TimersBase (this=0xb01f90) at /home/e10/e10/jamespjh/FabricHemeLb/build/hemelb-prefix/src/hemelb/reporting/Timers.h:90
#1  0x0000000000000000 in ?? ()
```

and the actual hemelb gives a sensible lack-of-MPI error (since I'm just running on a login node):

```

(gdb) run
Starting program: /nfs02/e10/e10/jamespjh/FabricHemeLb/build/hemelb-prefix/src/hemelb-build/hemelb 
[debugging using libthread_db enabled](Thread)
[Dec 22 18:33:38 2011](Thu) [c0-0c2s6n2] Fatal error in MPI_Init: Other MPI error, error stack:
MPIR_Init_thread(402): 
MPID_Init(123).......: channel initialization failed
MPID_Init(439).......:  PMI2 init failed: 1 
Attempting to use an MPI routine before initializing MPICH

```

**Comment by schmie** [comment]
**Comment by jamespjh on 23 Dec 2011 09:51 UTC**
I was WAY wrong in my analysis here. CTemplate autoconfigure can set itself up to handle the environment. I just wasn't telling it to use the cray compilers before running its autoconfigure step.

Setting export CXX=CC before running the configure step for ctemplate stops it looking for TR1!

So all of the above panic was irrelevant.

**Comment by schmie** [comment]
**Comment by jamespjh on 23 Dec 2011 10:49 UTC**
Also need to set LD=CC.

**Comment by schmie** [comment]
**Modified by jamespjh on 23 Dec 2011 10:51 UTC**

**Comment by schmie** [comment]
**Comment by hywel on 23 Dec 2011 11:05 UTC**
Nice one - well worked out.

**Comment by schmie** [comment]
**Comment by hywel on 7 Mar 2012 20:30 UTC**
Milestone 0.3 deleted
