### ISSUE TITLE
setuptool not working on default branch

### ISSUE THREAD

**Issue by schmie** [schmie/hemeMove#149]
**Reported by jamespjh on 19 Jan 2012 16:53 UTC**
```

(gdb) bt
#0  0x0106e893 in vtkDataArrayTemplate<float>::GetTuple ()
#1  0x0b8f0514 in Vec3<double>::operator- () at /Users/jamespjh/devel/ccs/hemelb/Tools/setuptool/HemeLbSetupTool/Model/Generation/Index.h:122
#2  0x0b8f0514 in ConfigGenerator::ClassifySite (this=0xa18ffd0, site=@0xc5779e0) at vtkPoints.h:150
#3  0x0b8f0a03 in ConfigGenerator::Execute (this=0xa18ffd0) at HemeLbSetupTool/Model/Generation/ConfigGenerator.cpp:59
#4  0x0b90065f in SWIG_Py_Void [inlined] () at /Users/jamespjh/devel/ccs/hemelb/Tools/setuptool/HemeLbSetupTool/Model/Generation/Wrap.cpp:7219
#5  0x0b90065f in _wrap_ConfigGenerator_Execute (args=0x2c8c90) at HemeLbSetupTool/Model/Generation/Wrap.cpp:7220
#6  0x000ca830 in PyEval_EvalFrameEx ()
#7  0x000cc0ee in PyEval_EvalFrameEx ()
#8  0x000cc0ee in PyEval_EvalFrameEx ()
#9  0x000cc0ee in PyEval_EvalFrameEx ()
#10 0x000cc91a in PyEval_EvalCodeEx ()
#11 0x000ccaa7 in PyEval_EvalCode ()
#12 0x000f1248 in PyRun_FileExFlags ()
#13 0x000f2173 in PyRun_SimpleFileExFlags ()
#14 0x0010b018 in Py_Main ()
#15 0x00001fb6 in ?? ()

```

**Comment by schmie** [comment]
**Comment by jamespjh on 20 Jan 2012 11:42 UTC**
Further investigation -- the problem occurs when using the cylinder.pro from blood, but not when using a profile I made with the same STL file.

**Comment by schmie** [comment]
**Comment by jamespjh on 20 Jan 2012 12:48 UTC**
When I make a profile of my own, with randomly placed Iolets, it works.

But when I place them exactly where the other file had them, it dies.

**Comment by schmie** [comment]
**Comment by jamespjh on 20 Jan 2012 12:58 UTC**
If I turn the normal to the inlet just slightly, so that it has normal (0,0.1,1) not (0,0,1), it doesn't crash.

**Comment by schmie** [comment]
**Modified by jamespjh on 20 Jan 2012 16:05 UTC**

**Comment by schmie** [comment]
**Comment by jamespjh on 9 Feb 2012 11:50 UTC**
This is the inside/outside bug, and is dup.
