### ISSUE TITLE
Hector segfault on regression tests

### ISSUE THREAD

**Issue by schmie** [schmie/hemeMove#309]
**Reported by hywel on 23 Jun 2012 08:15 UTC**
Looks like it could be a result of the new Net architecture. This is all the info I was about to glean from the core dump:

```
Program terminated with signal 11, Segmentation fault.
#0  memcpy () at ../sysdeps/x86_64/memcpy.S:196
196	../sysdeps/x86_64/memcpy.S: No such file or directory.
	in ../sysdeps/x86_64/memcpy.S
(gdb) 
(gdb) 
(gdb) info stack
#0  memcpy () at ../sysdeps/x86_64/memcpy.S:196
#1  0x0000000000692e46 in MPIDI_CH3U_Receive_data_found ()
#2  0x000000000069e4e0 in MPIDI_CH3_PktHandler_EagerSend ()
#3  0x000000000069175a in MPIDI_CH3I_Progress ()
#4  0x000000000060d40f in MPIC_Wait ()
#5  0x000000000060d968 in MPIC_Recv ()
#6  0x00000000005ff8aa in MPIR_Gatherv ()
#7  0x00000000006219dc in MPIR_CRAY_Gatherv ()
#8  0x00000000005ffa37 in MPIR_Gatherv_impl ()
#9  0x00000000005ffeb8 in PMPI_Gatherv ()
#10 0x00000000004b3cc4 in hemelb::geometry::DecompositionBase<hemelb::net::Net>::DecompositionBase (this=<optimized out>, 
    blockCount=<optimized out>, readBlock=<optimized out>, areadingGroupSize=<optimized out>, anet=<optimized out>, 
    comm=<optimized out>, rank=<optimized out>, size=<optimized out>)
    at /home/e10/e10/hywel/FabricHemeLb/build/hemelb-prefix/src/hemelb/geometry/Decomposition.hpp:74
#11 0x00007fff4c000809 in ?? ()
#12 0x0000000000000000 in ?? ()
(gdb) 
```

**Comment by schmie** [comment]
**Comment by hywel on 27 Jun 2012 19:31 UTC**
Fixed in dfbdc45a7a70.

I think this bug might have been getting in the way of doing production runs.

**Comment by schmie** [comment]
**Comment by hywel on 27 Jun 2012 19:32 UTC**
Derek, please have a look at this and review it.

Cheers

**Comment by schmie** [comment]
**Modified by jamespjh on 2 Jul 2012 11:18 UTC**

**Comment by schmie** [comment]
**Comment by jamespjh on 2 Jul 2012 11:44 UTC**
Hywel's analysis is correct, that this is a problem with large displacements in MPI.

http://stackoverflow.com/questions/10568662/error-on-mpi-scatterv-with-long-displacements

It's not a problem for the coalesced comms, cos datatype definition uses MPI_Aint, which fit any difference.

But gather only allows integer displacements, which breaks if the memory is far apart.

The workaround is not as pretty as a vector-of-vectors based interface, but is necessary.

Sad.

**Comment by schmie** [comment]
**Comment by hywel on 2 Jul 2012 17:10 UTC**
Reviewed; closing.
