### ISSUE TITLE
KeyError: 'fields'

### ISSUE THREAD

**Issue by schmie** [schmie/hemeMove#372]
**Reported by dholmes on 9 Aug 2012 11:40 UTC**
I attempted to get the diff on the description ticket #399 comment 4.

==== How to Reproduce ====

While doing a GET operation on `/ticket/399`, Trac issued an internal error.

''(please provide additional details here)''

Request parameters:
```
{'action': u'diff', 'id': u'399', 'version': u'4'}
```

User agent: `Mozilla/5.0 (Windows NT 6.1; WOW64; rv:11.0) Gecko/20100101 Firefox/11.0`

==== System Information ====
''System information not available''

==== Enabled Plugins ====
''Plugin information not available''

==== Python Traceback ====
```
Traceback (most recent call last):
  File "/usr/local/lib/python2.6/dist-packages/Trac-0.12.2-py2.6.egg/trac/web/main.py", line 511, in _dispatch_request
    dispatcher.dispatch(req)
  File "/usr/local/lib/python2.6/dist-packages/Trac-0.12.2-py2.6.egg/trac/web/main.py", line 248, in dispatch
    self._post_process_request(req, *resp)
  File "/usr/local/lib/python2.6/dist-packages/Trac-0.12.2-py2.6.egg/trac/web/main.py", line 357, in _post_process_request
    resp = f.post_process_request(req, *resp)
  File "/usr/lib/pymodules/python2.6/mastertickets/web_ui.py", line 64, in post_process_request
    for field, field_data in change['fields'].iteritems():
KeyError: 'fields'
```

**Comment by schmie** [comment]
**Comment by hywel on 10 Aug 2012 09:57 UTC**
This is a bug in the !MasterTickets plugin, fixed in 3.0

http://trac-hacks.org/ticket/6495

Will look into upgrading that plugin.

**Comment by schmie** [comment]
**Comment by hywel on 10 Aug 2012 10:34 UTC**
Done.
